pretty_gpx/drawing/poster_image_cache.py, pretty_gpx/gpx/augmented_gpx_data.py, pretty_gpx/gpx/gpx_track.py
Hi,
I have add the support for drawing elevation profile in distance rather than in points.
It resolves the issue https://github.com/ThomasParistech/pretty-gpx/issues/3
=> feat: add elevation profile function of distance and not time

.github/workflows/check.yml
=> ci: Run linter check when pushing to main

pretty_gpx/common/drawing/drawing_data.py, pretty_gpx/mountain/augmented_gpx_data.py, pretty_gpx/mountain/drawing/poster_image_cache.py, pretty_gpx/mountain/mountain_vertical_layout.py
- add LineCollection DrawingData
- dataclass.asdict returns a deepcopy of all the fields, which is pretty slow for heavy objets like LineCollectionData
- minor fixes
=> perf: Improve drawing figure perf

.github/workflows/validate-pr-title.yml
=> bug: Fix PR title validator for forked repos

.devcontainer/requirements.txt, pretty_gpx/city/city_drawing_figure.py, pretty_gpx/city/data/rivers.py, pretty_gpx/city/drawing/theme_colors.py, pretty_gpx/city/wip_city_sample.py, pretty_gpx/common/data/overpass_processing.py, pretty_gpx/common/drawing/drawing_data.py
Add rivers in city mode
Add the rivers to the city poster
See https://github.com/ThomasParistech/pretty-gpx/pull/9 for the discussion
=> feat: ✨ Add rivers in city mode

.devcontainer/requirements.txt, pretty_gpx/city/data/rivers.py, pretty_gpx/city/data/roads.py, pretty_gpx/city/wip_city_sample.py, pretty_gpx/common/data/overpass_request.py
Create a single overpass query separated with "count" statement and do a single download from overpass API
https://github.com/ThomasParistech/pretty-gpx/issues/15
Time to get a plot with roads and rivers is now around 15 seconds. 
Change not applied on the mountain mode, there is still the old overpass query function
=> perf: Do a single overpass request in city mode

pretty_gpx/city/data/rivers.py, pretty_gpx/common/data/overpass_processing.py
The bay and ocean were not drawn as well as some rivers that are not described with area but only with lines in OSM.
Bay and ocean as well as lakes are added.
And the small rivers are drawn with a fix length (=8m)
=> feat: add ocean/bay and add small rivers

pretty_gpx/common/data/overpass_processing.py, pretty_gpx/common/data/overpass_request.py, pretty_gpx/common/utils/utils.py
* Upgrade the merging algorithm to switch from a O(n^2) to O(n*log(n)) on average, this improvement was not needed before because rivers where small lists but it is needed for railways because lists are much larger and merging is required to create the sleepers for railways
* The concept is to use a Hash table to find the point that are close to each other. To do so, we use a tolerance epsilon and have a hashing function that is proportionnal to the position on a plane. A Segment class is introduced to access more easily to the data used (first and last point only)
See https://github.com/ThomasParistech/pretty-gpx/pull/21 for working sample
=> perf: update merging algorithm

examples/running/route_4_chateaux.gpx, pretty_gpx/city/city_drawing_figure.py, pretty_gpx/city/data/forests.py, pretty_gpx/city/data/rivers.py, pretty_gpx/city/drawing/theme_colors.py, pretty_gpx/city/wip_city_sample.py, pretty_gpx/common/data/overpass_processing.py, pretty_gpx/common/data/overpass_request.py, pretty_gpx/common/utils/utils.py
* Display forests and farmlands to make run in the countryside prettier.
* Enhance logs for rivers
* Add in logs the size of downloaded data
Merge after https://github.com/ThomasParistech/pretty-gpx/pull/27
=> feat: add forests

pretty_gpx/common/data/overpass_request.py, pretty_gpx/common/gpx/gpx_bounds.py, pretty_gpx/common/gpx/gpx_track.py, pretty_gpx/common/layout/base_vertical_layout.py, pretty_gpx/common/utils/logger.py, pretty_gpx/common/utils/nicegui_helper.py, pretty_gpx/main.py, pretty_gpx/mountain/data/augmented_gpx_data.py, pretty_gpx/mountain/data/elevation_map.py, pretty_gpx/mountain/drawing/poster_image_cache.py
Skip tracks with too large areas and handle failed file processing in the gui
=> feat: Catch errors during file processing

pretty_gpx/common/drawing/elevation_stats_section.py, pretty_gpx/common/gpx/gpx_bounds.py, pretty_gpx/common/layout/elevation_vertical_layout.py, pretty_gpx/mountain/drawing/poster_image_cache.py, pretty_gpx/mountain/mountain_vertical_layout.py
- share elevation profile drawing
- simplify poly before drawing
update of fillpoly timing: 700ms -> 7ms :zap:
=> perf: Speed up elevation profile fillPoly

pretty_gpx/city/city_vertical_layout.py, pretty_gpx/city/wip_city_sample.py, pretty_gpx/mountain/drawing/poster_image_cache.py
Missing commit in Ele poly simplification in PR https://github.com/ThomasParistech/pretty-gpx/pull/31 
=> perf: Actually use the ele poly simplifcation!

pretty_gpx/common/drawing/elevation_stats_section.py
For route des 4 chateaux, the profile is shorter than the n sampling. 
Fix the case when downsampling is not needed
=> fix: elevation downsampling

pretty_gpx/explore_new_color_themes.py, pretty_gpx/main.py, pretty_gpx/rendering_modes/city/city_drawing_figure.py, pretty_gpx/rendering_modes/city/drawing/city_drawing_params.py, pretty_gpx/rendering_modes/city/wip_city_sample.py, pretty_gpx/rendering_modes/mountain/drawing/mountain_poster_image_cache.py
Prepare the city gui by specifying Mountain/City in the only class that had not this feature (because there were not a city file corresponding to it).
Refactor the color management of the plotter function for cities
Add a city drawing params that will be used in the city poster
=> refactor: Prepare the city gui

.devcontainer/requirements.txt, .dockerignore, .vscode/.mypy.ini, pretty_gpx/fly/fly_io_setup.py, pretty_gpx/main.py, pretty_gpx/simplify_gpx.py, scripts/fly_deploy.sh
- Fix nicegui port
- Use Multiple fly.io Instances
- Lighten Docker image (4.2GB -> 2.5GB)
=> perf: Use Multiple fly.io Instances and Lighten Docker image

.devcontainer/Dockerfile, .github/workflows/check.yml, .vscode/.mypy.ini, pretty_gpx/common/drawing/color_theme.py, pretty_gpx/common/structure.py, pretty_gpx/ui/pages/template/elements/ui_input.py, pretty_gpx/ui/pages/template/elements/ui_toggle.py, pretty_gpx/ui/pages/template/ui_cache.py
=> ci: bump python 3.10 to 3.11

README.md, pyproject.toml
=> ci: Python 3.11

pretty_gpx/common/data/overpass_request.py, pretty_gpx/common/gpx/gpx_bounds.py, pretty_gpx/common/gpx/gpx_distance.py, pretty_gpx/common/gpx/gpx_track.py, pretty_gpx/common/layout/base_vertical_layout.py, pretty_gpx/common/utils/asserts.py, pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
- Use correct XY distance instead of degree distance on distorted lat/lon
- Add "ele" info on Col des Boeufs on OpenStreetmap
- Use margin around GpxBounds before querying passes, to retrieve Col d'azet
=> fix: Fix missing Col des Boeufs/Col d'Azet and use correct XY distance from lat/lon

pretty_gpx/common/drawing/base_drawing_figure.py, pretty_gpx/common/drawing/drawing_data.py, pretty_gpx/common/drawing/fonts.py, pretty_gpx/common/drawing/text_allocation.py, pretty_gpx/common/gpx/gpx_bounds.py, pretty_gpx/common/gpx/gpx_distance.py, pretty_gpx/rendering_modes/city/drawing/city_drawer.py, pretty_gpx/rendering_modes/city/drawing/city_drawing_config.py, pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py, pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_config.py
- Fix bug in XY distance (wrong lat)
- Add enum listing available fonts
-  Convert an annotation line to an arrow pointing to the corresponding marker
=> feat: Draw arrows pointing at mountain passes

pretty_gpx/common/data/overpass_request.py, pretty_gpx/common/data/place_name.py, pretty_gpx/common/drawing/text_allocation.py, pretty_gpx/common/utils/profile.py, pretty_gpx/rendering_modes/city/data/forests.py, pretty_gpx/rendering_modes/city/data/rivers.py, pretty_gpx/rendering_modes/city/data/roads.py, pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py, pretty_gpx/rendering_modes/mountain/data/mountain_huts.py, pretty_gpx/rendering_modes/mountain/data/mountain_passes.py, pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
Use faster OverpassQuery for mountain huts and passes
Before
After:
=> perf: Use faster OverpassQuery for mountain huts and passes

pretty_gpx/common/gpx/gpx_distance.py, pretty_gpx/rendering_modes/city/data/bridges.py
Detect City Bridges
berlin
new york
chicago
paris centre
=> feat: Detect City Bridges

.devcontainer/requirements.txt, .github/workflows/check.yml, pretty_gpx/common/utils/asserts.py, pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py, pretty_gpx/test/test_bridges.py, pretty_gpx/test/test_city_pois.py, pretty_gpx/test/test_mountain_passes.py, scripts/run_pytest.sh
- Setup Pytest GithubAction
- Test Bridge, Points-of-Interest and Mountain Passes
=> test: Add Pytests

pretty_gpx/common/drawing/text_allocation.py, pretty_gpx/common/gpx/gpx_distance.py, pretty_gpx/common/gpx/gpx_track.py, pretty_gpx/common/structure.py, pretty_gpx/common/utils/plt.py, pretty_gpx/rendering_modes/city/data/bridges.py, pretty_gpx/rendering_modes/city/data/city_pois.py, pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py, pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
Compute Annotation Arrows inside text_allocation
=> refactor: Compute Annotation Arrows inside text_allocation

pretty_gpx/test/test_city_ui.py, pretty_gpx/test/test_mountain_ui.py, scripts/run_mypy.sh
add pytests for city/mountain cache ui
=> test: add pytests for city/mountain cache ui

.devcontainer/requirements.txt
See PR https://github.com/ckjellson/textalloc/pull/31
Issue https://github.com/ThomasParistech/pretty-gpx/issues/70 
=> fix: Correctly handle vertical alignment in textalloc

pretty_gpx/common/drawing/utils/drawer.py, pretty_gpx/common/utils/utils.py, pretty_gpx/rendering_modes/mountain/data/mountain_passes.py
Issue https://github.com/ThomasParistech/pretty-gpx/issues/80
=> fix: Handle float ele

pretty_gpx/common/drawing/components/annotated_scatter.py, pretty_gpx/common/drawing/utils/scatter_point.py, pretty_gpx/common/request/osm_name.py, pretty_gpx/common/request/overpass_processing.py, pretty_gpx/rendering_modes/city/data/city_pois.py, pretty_gpx/rendering_modes/mountain/data/mountain_huts.py, pretty_gpx/test/test_bridges.py, pretty_gpx/test/test_city_pois.py
Use shortest possible osm name to make text allocation easier
=> feat:  Use shortest possible osm name

pretty_gpx/ui/pages/multi_mountain/page.py, pretty_gpx/ui/pages/template/ui_icon_toggle.py
- add generic icon toggle element
- allow multimountain poster to select hut icon
https://github.com/user-attachments/assets/5a063699-4f31-4f9b-b59b-13493b56cb69
=> feat: Add icon toggle for Mountain Hut

.devcontainer/requirements.txt
=> fix: Fix nicegui

.devcontainer/requirements.txt, scripts/mac_setup.sh
Add mac setup script without docker
=> fix: Add mac setup script without docker
